#### Step 1: import necessary Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### Step 2: Import dataset

In [2]:
Dataset=pd.read_csv('C:/Users/SUBHAM/Desktop/projects/ML/Data/KNN Data.csv')

In [3]:
Dataset.head()

Age  Salary  Purchased Plot
0   22   22990               0
1   38   24200               0
2   29   52030               0
3   30   68970               0
4   22   91960               0

In [4]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             400 non-null    int64
 1   Salary          400 non-null    int64
 2   Purchased Plot  400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [5]:
Dataset.isnull().sum()

Age               0
Salary            0
Purchased Plot    0
dtype: int64

#### Step 3: Divide Dataset into Feature Matrix and output vector

In [6]:
X=Dataset.iloc[:,:-1].values
Y=Dataset.iloc[:,-1].values

#### Step 4: Split the dataset into training and testing set

In [7]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2)

#### Step 5: Building a KNN Classifier

In [8]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier()

In [9]:
KNN.fit(xtrain,ytrain)

KNeighborsClassifier()

#### Step 6: Validate the model with test input

In [10]:
ypred=KNN.predict(xtest)

In [11]:
ypred

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0], dtype=int64)

In [12]:
ytest

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

#### Step 7: Performance Metrix in term of confusion matix

In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score
CM=confusion_matrix(ytest,ypred)
CM

array([[52,  6],
       [ 5, 17]], dtype=int64)

In [14]:
ytest.shape

(80,)

In [15]:
print(accuracy_score(ytest,ypred))

0.8625
