#### Step 1: import necessary Library

In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### Step 2: Import dataset

In [34]:
Dataset=pd.read_csv('C:/Users/SUBHAM/Desktop/projects/ML/Data/KNN Data.csv')

In [35]:
Dataset.head()

Age  Salary  Purchased Plot
0   22   22990               0
1   38   24200               0
2   29   52030               0
3   30   68970               0
4   22   91960               0

In [36]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             400 non-null    int64
 1   Salary          400 non-null    int64
 2   Purchased Plot  400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [37]:
Dataset.isnull().sum()

Age               0
Salary            0
Purchased Plot    0
dtype: int64

#### Step 3: Divide Dataset into Feature Matrix and output vector

In [38]:
X=Dataset.iloc[:,:-1].values
Y=Dataset.iloc[:,-1].values

#### Step 4: Split the dataset into training and testing set

In [39]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,Y,test_size=0.2)

#### Step 5: Building a KNN Classifier

In [40]:
from sklearn.neighbors import KNeighborsClassifier
KNN=KNeighborsClassifier()

In [41]:
KNN.fit(xtrain,ytrain)

KNeighborsClassifier()

#### Step 6: Validate the model with test input

In [42]:
ypred=KNN.predict(xtest)

In [43]:
ypred

array([0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [44]:
ytest

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

#### Step 7: Performance Metrix in term of confusion matix

In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score
CM=confusion_matrix(ytest,ypred)
CM

array([[36,  5],
       [16, 23]], dtype=int64)

In [46]:
ytest.shape

(80,)

In [47]:
print(accuracy_score(ytest,ypred))

0.7375


### Naive Baye's Decision Tree and Random Forest as Classifier

In [48]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
gnb=GaussianNB()
dtc=DecisionTreeClassifier(criterion="entropy",max_depth=3)
rfc=RandomForestClassifier(n_estimators=700,criterion='entropy')

#### Building Naive Baye's Classifier

In [49]:
gnb.fit(xtrain,ytrain)

GaussianNB()

In [50]:
ypred_gnb=gnb.predict(xtest)

#### Testing Score and

In [51]:
print(gnb.score(xtest,ytest))
print(gnb.score(xtrain,ytrain))

0.825
0.89375


In [52]:
from sklearn.metrics import precision_score, confusion_matrix, accuracy_score, mean_squared_error, f1_score, recall_score,classification_report

In [53]:
print(confusion_matrix(ytest, ypred_gnb))
print(accuracy_score(ytest, ypred_gnb))
print(precision_score(ytest, ypred_gnb,average=None,zero_division=0))
print(f1_score(ytest, ypred_gnb))
print(mean_squared_error(ytest, ypred_gnb))

[[38  3]
 [11 28]]
0.825
[0.7755102  0.90322581]
0.8
0.175


#### Classification Report

In [54]:
print(classification_report(ytest,ypred_gnb,zero_division=0))

              precision    recall  f1-score   support

           0       0.78      0.93      0.84        41
           1       0.90      0.72      0.80        39

    accuracy                           0.82        80
   macro avg       0.84      0.82      0.82        80
weighted avg       0.84      0.82      0.82        80



#### Similarly do it for DT and random forest. Compare all models and comment on which model need to be used for the given dataset

In [55]:
dtc.fit(xtrain,ytrain)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [56]:
ypred_dtc=dtc.predict(xtest)

In [57]:
print(dtc.score(xtest,ytest))
print(dtc.score(xtrain,ytrain))

0.8625
0.921875


In [58]:
print(confusion_matrix(ytest, ypred_dtc))
print(accuracy_score(ytest, ypred_dtc))
print(precision_score(ytest, ypred_dtc,average=None,zero_division=0))
print(f1_score(ytest, ypred_dtc))
print(mean_squared_error(ytest, ypred_dtc))

[[38  3]
 [ 8 31]]
0.8625
[0.82608696 0.91176471]
0.8493150684931507
0.1375


In [59]:
print(classification_report(ytest,ypred_dtc,zero_division=0))

              precision    recall  f1-score   support

           0       0.83      0.93      0.87        41
           1       0.91      0.79      0.85        39

    accuracy                           0.86        80
   macro avg       0.87      0.86      0.86        80
weighted avg       0.87      0.86      0.86        80



In [60]:
rfc.fit(xtrain,ytrain)

RandomForestClassifier(criterion='entropy', n_estimators=700)

In [61]:
ypred_rfc=rfc.predict(xtest)

In [62]:
print(rfc.score(xtest,ytest))
print(rfc.score(xtrain,ytrain))

0.875
0.996875


In [63]:
print(confusion_matrix(ytest, ypred_rfc))
print(accuracy_score(ytest, ypred_rfc))
print(precision_score(ytest, ypred_rfc,average=None,zero_division=0))
print(f1_score(ytest, ypred_rfc))
print(mean_squared_error(ytest, ypred_rfc))

[[37  4]
 [ 6 33]]
0.875
[0.86046512 0.89189189]
0.868421052631579
0.125


In [64]:
print(classification_report(ytest,ypred_rfc,zero_division=0))

              precision    recall  f1-score   support

           0       0.86      0.90      0.88        41
           1       0.89      0.85      0.87        39

    accuracy                           0.88        80
   macro avg       0.88      0.87      0.87        80
weighted avg       0.88      0.88      0.87        80

